version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: platform_backend:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: +++++
    volumes:
      - ./app/backend:/app

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    image: platform_frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
